matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "2.7_with_system_site_packages"
    - os: osx
      language: generic

install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:lazka/dumpingplace; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -q; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y quodlibet exfalso xvfb pep8 pyflakes; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget http://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-3.5.1.zip; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then unzip QuodLibet-3.5.1.zip; fi

script:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then xvfb-run -a ./quodlibet/setup.py test; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then xvfb-run -a ./quodlibet/setup.py quality; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./QuodLibet.app/Contents/MacOS/run ./quodlibet/setup.py test; fi
