matrix:
  allow_failures:
    - python: "3.4_with_system_site_packages"
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "2.7_with_system_site_packages"
      env: PYTHON="python2"
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "3.4_with_system_site_packages"
      env: PYTHON="python3"
    - os: osx
      language: generic

install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:lazka/dumpingplace; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -q; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y quodlibet exfalso xvfb pep8 pyflakes python3-mutagen python3-gi python3-gi-cairo; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip install --upgrade pep8; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget http://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-3.5.1.zip; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then unzip -qq QuodLibet-3.5.1.zip; fi

script:
 - cd quodlibet
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then xvfb-run -a $PYTHON ./setup.py test; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then xvfb-run -a $PYTHON ./setup.py quality; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ../QuodLibet.app/Contents/MacOS/run setup.py test; fi
