sudo: required
dist: trusty
language: python
python:
  - "2.7"

install:
 - sudo apt-add-repository -y ppa:lazka/dumpingplace
 - sudo apt-get update -q
 - apt-cache depends quodlibet | sed -nre 's/\s+Depends. ([a-z0-9\.]+)/\1/p' | xargs sudo apt-get install -y
 - sudo apt-get install -y xvfb libgpod4 python-feedparser python-pyparsing
 - pip install --upgrade pyflakes pep8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
 - cd quodlibet
 - ./setup.py test
 - ./setup.py quality