sudo: required
dist: trusty
language: python
python:
  - "2.7"

install:
 - sudo apt-add-repository -y ppa:lazka/dumpingplace
 - sudo apt-get update -q
 - "apt-cache depends quodlibet | sed -nre 's/\s+Depends: ([a-z0-9\.]+)/\1/p' | xargs sudo apt-get install -y"
 - sudo apt-get install -y libgpod4 python-feedparser python-pyparsing
 - pip install --upgrade pyflakes pep8

before_script:
 - sudo start xvfb

script:
 - cd quodlibet
 - ./setup.py test
 - ./setup.py quality