sudo: required
dist: trusty
language: python
python:
  - "2.7"

install:
 - sudo add-apt-repository -y ppa:lazka/dumpingplace
 - sudo apt-get update -q
 - sudo apt-get install quodlibet exfalso xvfb pep8 pyflakes

script:
 - cd quodlibet
 - xvfb-run -a ./setup.py test
 - xvfb-run -a ./setup.py quality
